import { v1 as uuid, v1 } from "uuid"

export const dummyData = [
    {
      title: "Weigthing class",
      location: "Y.M.C.A",
      filterClass: "weight",
      filterTime: "morning",
      image: "https://ironstonestrength.com/wp-content/uploads/IMG_5320-1600x1067.jpg",
      time: "8am - 12am",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Weigthing class",
      location: "Y.M.C.A",
      filterClass: "weight",
      filterTime: "afternoon",
      image: "https://ironstonestrength.com/wp-content/uploads/IMG_2902-1600x1067.jpg",
      time: "12am - 6pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Weigthing class",
      location: "Y.M.C.A",
      filterClass: "weight",
      filterTime: "night",
      image: "https://ironstonestrength.com/wp-content/uploads/IMG_5036-1600x1067.jpg",
      time: "5pm - 10pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Weigthing class",
      location: "Y.M.C.A",
      filterClass: "weight",
      filterTime: "morning",
      image: "https://i.ytimg.com/vi/yDPeizm1U_Y/maxresdefault.jpg",
      time: "8am - 1pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Weigthing class",
      location: "Y.M.C.A",
      filterClass: "weight",
      filterTime: "afternoon",
      image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/weightlifting-class-togetherness-royalty-free-image-504376782-1540223279.jpg",
      time: "2pm - 6pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Weigthing class",
      location: "Y.M.C.A",
      filterClass: "weight",
      filterTime: "morning",
      image: "https://crossfittaino.com/wp-content/uploads/2020/10/Weightlifting2.jpg",
      time: "8am - 1pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Weigthing class",
      location: "Y.M.C.A",
      filterClass: "weight",
      filterTime: "afternoon",
      image: "https://thecentercville.org/event_images/boot_camp_1.jpg",
      time: "1pm - 7pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Running class",
      location: "Y.M.C.A",
      filterClass: "run",
      filterTime: "morning",
      image: "https://classpass.com/blog/wp-content/uploads/2019/06/shutterstock_749337043.jpg",
      time: "8am - 12am",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Running class",
      location: "Y.M.C.A",
      filterClass: "run",
      filterTime: "morning",
      image: "https://www.technogym.com/wpress/wp-content/uploads/2020/03/header-skillmill-HIIT-mobile-1.jpg",
      time: "10am - 2pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Running class",
      location: "Y.M.C.A",
      filterClass: "run",
      filterTime: "afternoon",
      image: "https://images.squarespace-cdn.com/content/v1/5cec8674d7ab740001265625/1561508212484-71UWPUG72VZHL84AXBXZ/website.jpg",
      time: "1pm - 5pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Running class",
      location: "Y.M.C.A",
      filterClass: "run",
      filterTime: "afternoon",
      image: "https://images.squarespace-cdn.com/content/v1/5f2b5bc5661ed32e97506c9e/1597173602640-F2NOAORK8WZ5UD8O2R0K/for+all+chilfren+runners%2C+Running+Club+Tampa%2C+Run+Tampa",
      time: "3pm - 7pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Swimming class",
      filterClass: "swim",
      filterTime: "morning",
      location: "Y.M.C.A",
      image: "https://cdn.lessons.com/assets/images/bg/thumbs/swimming.jpg",
      time: "6am - 1pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Swimming class",
      filterClass: "swim",
      filterTime: "afternoon",
      location: "Y.M.C.A",
      image: "https://media.istockphoto.com/photos/female-coach-in-water-giving-group-of-children-swimming-lesson-in-picture-id1167733673?k=20&m=1167733673&s=170667a&w=0&h=RLlAP7Y7l8WC_O9SNHSFzc8uX_wg6AigQ2so8IbxZUU=",
      time: "11am - 6pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Swimming class",
      filterClass: "swim",
      filterTime: "night",
      location: "Y.M.C.A",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVRXrOamy56t4d4yPYctln_sb47yAzP7_5yw&usqp=CAU",
      time: "5pm - 10pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Swimming class",
      filterClass: "swim",
      filterTime: "morning",
      location: "Y.M.C.A",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsQ0kQ0suQpfRmyvsqQLXuV1S4idIffWUjaw&usqp=CAU",
      time: "8am - 1pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Cycling class",
      filterClass: "cycle",
      filterTime: "morning",
      location: "Y.M.C.A",
      image: "https://www.chicagotribune.com/resizer/w5WE9G3WBfPRPM55YHWrxX9ktcQ=/1200x0/top/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/PK6N5ACHP5CMDK5TSY6HP6NJZI.jpg",
      time: "7am - 1pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Cycling class",
      filterClass: "cycle",
      filterTime: "afternoon",
      location: "Y.M.C.A",
      image: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/group-of-fit-people-working-out-on-spinning-class-royalty-free-image-916146326-1541706732.jpg",
      time: "1pm - 6pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Cycling class",
      filterClass: "cycle",
      filterTime: "afternoon",
      location: "Y.M.C.A",
      image: "https://mountainsidefitness.com/wp-content/uploads/2019/10/Cycle-v2.jpg",
      time: "3pm - 8pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Cycling class",
      filterClass: "cycle",
      filterTime: "night",
      location: "Y.M.C.A",
      image: "https://media.timeout.com/images/103738279/image.jpg",
      time: "4pm - 8pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
    {
      title: "Cycling class",
      filterClass: "cycle",
      filterTime: "morning",
      filterLocation: "",
      location: "Y.M.C.A",
      image: "http://static1.squarespace.com/static/5b6dc00c4611a0fe8ad02bfb/t/5e0a22551b797629a1a8d231/1577722455921/hero-google-studio-purple.jpg?format=1500w",
      time: "7am - 3pm",
      id: v1(),
      schedule: "Mon, Wed, Fri", 
      member: "19/20",
      description: "eight training is a type of strength training that uses weights for resistance. By creating a stress to the muscles performed with free weights (e.g. barbells and dumbbells) or by using weight machines, these exercises will enable muscles to be activated and get stronger.Effective weight training depends on proper technique. You might learn weight training techniques by watching friends or others in the gym — but sometimes what you see may not be safe or truly effective. Incorrect weight training technique can lead to sprains, strains, fractures or other painful injuries that hamper your weight training efforts. For safety reasons, it is advisable for new members to schedule sessions with a personal trainer before embarking on your weight training program.",
    },
  ];

